/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

#include <machine/registerset.h>

#if defined(CONFIG_ARCH_X86_64)
#define FAULT_MESSAGE_SYSCALL_INITIALIZER \
    RAX, RBX, RCX, RDX, RSI, RDI, RBP, R8, R9, R10, R11, R12, R13, R14, R15, \
    FaultIP, RSP, FLAGS
#define FAULT_MESSAGE_EXCEPTION_INITIALIZER FaultIP, RSP, FLAGS
#ifdef CONFIG_KERNEL_MCS
#define FAULT_MESSAGE_TIMEOUT_INITIALIZER \
    FaultIP, RSP, FLAGS, RAX, RBX, RCX, RDX, RSI, RDI, RBP, R8, R9, R10, R11, \
    R12, R13, R14, R15, TLS_BASE
#endif /* CONFIG_KERNEL_MCS */
#elif defined(CONFIG_ARCH_IA32)
#define FAULT_MESSAGE_SYSCALL_INITIALIZER \
    EAX, EBX, ECX, EDX, ESI, EDI, EBP, FaultIP, ESP, FLAGS
#define FAULT_MESSAGE_EXCEPTION_INITIALIZER FaultIP, ESP, FLAGS
#ifdef CONFIG_KERNEL_MCS
#define FAULT_MESSAGE_TIMEOUT_INITIALIZER \
    FaultIP, ESP, FLAGS, EAX, EBX, ECX, EDX, ESI, EDI, EBP, FS_BASE, GS_BASE
#endif /* CONFIG_KERNEL_MCS */
#elif defined(CONFIG_ARCH_AARCH64)
#define FAULT_MESSAGE_SYSCALL_INITIALIZER \
    X0, X1, X2, X3, X4, X5, X6, X7, FaultIP, SP_EL0, ELR_EL1, SPSR_EL1
#define FAULT_MESSAGE_EXCEPTION_INITIALIZER FaultIP, SP_EL0, SPSR_EL1
#ifdef CONFIG_KERNEL_MCS
#define FAULT_MESSAGE_TIMEOUT_INITIALIZER \
    FaultIP, SP_EL0, SPSR_EL1, X0, X1, X2, X3, X4, X5, X6, X7, X8, X16, X17, \
    X18, X29, X30, X9, X10, X11, X12, X13, X14, X15, X19, X20, X21, X22, X23, \
    X24, X25, X26, X27, X28
#endif /* CONFIG_KERNEL_MCS */
#elif defined(CONFIG_ARCH_AARCH32)
#define FAULT_MESSAGE_SYSCALL_INITIALIZER \
    R0, R1, R2, R3, R4, R5, R6, R7, FaultIP, SP, LR, CPSR
#define FAULT_MESSAGE_EXCEPTION_INITIALIZER FaultIP, SP, CPSR
#ifdef CONFIG_KERNEL_MCS
#define FAULT_MESSAGE_TIMEOUT_INITIALIZER \
    FaultIP, SP, CPSR, R0, R1, R8, R9, R10, R11, R12, R2, R3, R4, R5, R6, R7, \
    R14
#endif /* CONFIG_KERNEL_MCS */
#elif defined(CONFIG_ARCH_RISCV)
#define FAULT_MESSAGE_SYSCALL_INITIALIZER \
    FaultIP, SP, LR, a0, a1, a2, a3, a4, a5, a6
#define FAULT_MESSAGE_EXCEPTION_INITIALIZER FaultIP, SP
#ifdef CONFIG_KERNEL_MCS
#define FAULT_MESSAGE_TIMEOUT_INITIALIZER \
    FaultIP, LR, SP, GP, s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, a0, \
    a1, a2, a3, a4, a5, a6, a7, t0, t1, t2, t3, t4, t5, t6, TP
#endif /* CONFIG_KERNEL_MCS */
#else
#error "Unsupported architecture for fault_messages initialisers"
#endif

const register_t fault_messages[][MAX_MSG_SIZE] = {
    { FAULT_MESSAGE_SYSCALL_INITIALIZER },
    { FAULT_MESSAGE_EXCEPTION_INITIALIZER },
#ifdef CONFIG_KERNEL_MCS
    { FAULT_MESSAGE_TIMEOUT_INITIALIZER },
#endif
};
