
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:11 (project)"
    message: |
      The target system is: Generic -  - seL4CPU
      The host system is: Linux - 6.12.13 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:11 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/3.28.3/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1131 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:11 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
      Copyright (C) 2023 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:11 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4"
      binary: "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_SYSROOT: "/workspace/seL4-c89/preconfigured/X64_verified"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4'
        
        Run Build Command(s): /usr/bin/ninja -v cmTC_6fc29
        [1/2] /usr/bin/ccache /usr/bin/gcc --sysroot=/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4   -v -o CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj -c /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Using built-in specs.
        COLLECT_GCC=/usr/bin/gcc
        OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
        OFFLOAD_TARGET_DEFAULT=1
        Target: x86_64-linux-gnu
        Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.3.0-6ubuntu2~24.04' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-libstdcxx-backtrace --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-fG75Ri/gcc-13-13.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-fG75Ri/gcc-13-13.3.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
        Thread model: posix
        Supported LTO compression algorithms: zlib zstd
        gcc version 13.3.0 (Ubuntu 13.3.0-6ubuntu2~24.04) 
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '--sysroot=/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4' '-v' '-c' '-o' 'CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_6fc29.dir/'
         /usr/libexec/gcc/x86_64-linux-gnu/13/cc1 -quiet -v -imultiarch x86_64-linux-gnu -isysroot /workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4 /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c -quiet -dumpdir CMakeFiles/cmTC_6fc29.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -mtune=generic -march=x86-64 -version -fdiagnostics-color=always -fasynchronous-unwind-tables -fstack-protector-strong -Wformat -Wformat-security -fstack-clash-protection -fcf-protection -o /tmp/ccoDZ0nl.s
        GNU C17 (Ubuntu 13.3.0-6ubuntu2~24.04) version 13.3.0 (x86_64-linux-gnu)
        	compiled by GNU C version 13.3.0, GMP version 6.3.0, MPFR version 4.2.1, MPC version 1.3.1, isl version isl-0.26-GMP
        
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4/usr/local/include/x86_64-linux-gnu"
        ignoring nonexistent directory "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4/usr/local/include"
        ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/13/include-fixed/x86_64-linux-gnu"
        ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/13/include-fixed"
        ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/13/../../../../x86_64-linux-gnu/include"
        ignoring nonexistent directory "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4/usr/include/x86_64-linux-gnu"
        ignoring nonexistent directory "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4/usr/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/lib/gcc/x86_64-linux-gnu/13/include
        End of search list.
        Compiler executable checksum: 38987c28e967c64056a6454abdef726e
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '--sysroot=/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4' '-v' '-c' '-o' 'CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_6fc29.dir/'
         as -v --64 -o CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj /tmp/ccoDZ0nl.s
        GNU assembler version 2.42 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.42
        COMPILER_PATH=/usr/libexec/gcc/x86_64-linux-gnu/13/:/usr/libexec/gcc/x86_64-linux-gnu/13/:/usr/libexec/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/13/:/usr/lib/gcc/x86_64-linux-gnu/
        LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/13/:/usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/13/../../../../lib/:/usr/lib/gcc/x86_64-linux-gnu/13/../../../
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '--sysroot=/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4' '-v' '-c' '-o' 'CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.'
        [2/2] : && /usr/bin/ccache /usr/bin/cmake -E rm -f libcmTC_6fc29.a && /usr/bin/ccache /usr/bin/ar qc libcmTC_6fc29.a  CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj && /usr/bin/ccache /usr/bin/ranlib libcmTC_6fc29.a && :
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:11 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/usr/lib/gcc/x86_64-linux-gnu/13/include]
        end of search list found
        collapse include dir [/usr/lib/gcc/x86_64-linux-gnu/13/include] ==> [/usr/lib/gcc/x86_64-linux-gnu/13/include]
        implicit include dirs: [/usr/lib/gcc/x86_64-linux-gnu/13/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:159 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:11 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: '/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4']
        ignore line: []
        ignore line: [Run Build Command(s): /usr/bin/ninja -v cmTC_6fc29]
        ignore line: [[1/2] /usr/bin/ccache /usr/bin/gcc --sysroot=/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4   -v -o CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj -c /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Using built-in specs.]
        ignore line: [COLLECT_GCC=/usr/bin/gcc]
        ignore line: [OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa]
        ignore line: [OFFLOAD_TARGET_DEFAULT=1]
        ignore line: [Target: x86_64-linux-gnu]
        ignore line: [Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.3.0-6ubuntu2~24.04' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c ada c++ go d fortran objc obj-c++ m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-libstdcxx-backtrace --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32 m64 mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-fG75Ri/gcc-13-13.3.0/debian/tmp-nvptx/usr amdgcn-amdhsa=/build/gcc-13-fG75Ri/gcc-13-13.3.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2]
        ignore line: [Thread model: posix]
        ignore line: [Supported LTO compression algorithms: zlib zstd]
        ignore line: [gcc version 13.3.0 (Ubuntu 13.3.0-6ubuntu2~24.04) ]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '--sysroot=/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4' '-v' '-c' '-o' 'CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_6fc29.dir/']
        ignore line: [ /usr/libexec/gcc/x86_64-linux-gnu/13/cc1 -quiet -v -imultiarch x86_64-linux-gnu -isysroot /workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4 /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c -quiet -dumpdir CMakeFiles/cmTC_6fc29.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -mtune=generic -march=x86-64 -version -fdiagnostics-color=always -fasynchronous-unwind-tables -fstack-protector-strong -Wformat -Wformat-security -fstack-clash-protection -fcf-protection -o /tmp/ccoDZ0nl.s]
        ignore line: [GNU C17 (Ubuntu 13.3.0-6ubuntu2~24.04) version 13.3.0 (x86_64-linux-gnu)]
        ignore line: [	compiled by GNU C version 13.3.0  GMP version 6.3.0  MPFR version 4.2.1  MPC version 1.3.1  isl version isl-0.26-GMP]
        ignore line: []
        ignore line: [GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072]
        ignore line: [ignoring nonexistent directory "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4/usr/local/include/x86_64-linux-gnu"]
        ignore line: [ignoring nonexistent directory "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4/usr/local/include"]
        ignore line: [ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/13/include-fixed/x86_64-linux-gnu"]
        ignore line: [ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/13/include-fixed"]
        ignore line: [ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/13/../../../../x86_64-linux-gnu/include"]
        ignore line: [ignoring nonexistent directory "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4/usr/include/x86_64-linux-gnu"]
        ignore line: [ignoring nonexistent directory "/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4/usr/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /usr/lib/gcc/x86_64-linux-gnu/13/include]
        ignore line: [End of search list.]
        ignore line: [Compiler executable checksum: 38987c28e967c64056a6454abdef726e]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '--sysroot=/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4' '-v' '-c' '-o' 'CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_6fc29.dir/']
        ignore line: [ as -v --64 -o CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj /tmp/ccoDZ0nl.s]
        ignore line: [GNU assembler version 2.42 (x86_64-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.42]
        ignore line: [COMPILER_PATH=/usr/libexec/gcc/x86_64-linux-gnu/13/:/usr/libexec/gcc/x86_64-linux-gnu/13/:/usr/libexec/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/13/:/usr/lib/gcc/x86_64-linux-gnu/]
        ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/13/:/usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/13/../../../../lib/:/usr/lib/gcc/x86_64-linux-gnu/13/../../../]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '--sysroot=/workspace/seL4-c89/preconfigured/X64_verified/CMakeFiles/CMakeScratch/TryCompile-37HND4' '-v' '-c' '-o' 'CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.']
        ignore line: [[2/2] : && /usr/bin/ccache /usr/bin/cmake -E rm -f libcmTC_6fc29.a && /usr/bin/ccache /usr/bin/ar qc libcmTC_6fc29.a  CMakeFiles/cmTC_6fc29.dir/CMakeCCompilerABI.c.obj && /usr/bin/ccache /usr/bin/ranlib libcmTC_6fc29.a && :]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
